name: avengers_soundboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/character_images/
    - assets/soundbtns/sounds/ironman/

  fonts:
  - family: Gloria
    fonts:
    - asset: fonts/GloriaHallelujah-Regular.ttf

